# Run from project root:
#   .\scripts\setup-db.ps1
# Or pass password directly:
#   .\scripts\setup-db.ps1 -Password "your_postgres_password"

param(
    [string]$Password,
    [string]$DbName = "placement_focusbar",
    [string]$DbUser = "postgres",
    [string]$DbHost = "localhost",
    [int]$DbPort = 5432
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path $PSScriptRoot -Parent
Set-Location $ProjectRoot

$psql = "C:\Program Files\PostgreSQL\18\bin\psql.exe"
if (-not (Test-Path $psql)) {
    Write-Error "psql not found at $psql. Adjust the path in setup-db.ps1 for your PostgreSQL version."
}

if (-not $Password) {
    $secure = Read-Host "Enter PostgreSQL password for user '$DbUser'" -AsSecureString
    $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    )
}

if (-not $Password) {
    Write-Error "Password is required."
}

$env:PGPASSWORD = $Password

Write-Host "Testing connection..."
& $psql -U $DbUser -h $DbHost -p $DbPort -d postgres -c "SELECT 1;" | Out-Null
if ($LASTEXITCODE -ne 0) {
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    Write-Error "Connection failed. Check user/password."
}

Write-Host "Creating database '$DbName' if missing..."
$countSql = "SELECT COUNT(*) FROM pg_database WHERE datname = '$DbName';"
$dbCount = (& $psql -U $DbUser -h $DbHost -p $DbPort -d postgres -tAc $countSql).Trim()

if ($dbCount -eq "0") {
    & $psql -U $DbUser -h $DbHost -p $DbPort -d postgres -c "CREATE DATABASE $DbName;"
    if ($LASTEXITCODE -ne 0) {
        Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
        Write-Error "Failed to create database '$DbName'."
    }
    Write-Host "Database created."
} else {
    Write-Host "Database already exists."
}

Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue

Add-Type -AssemblyName System.Web
$encodedPassword = [System.Web.HttpUtility]::UrlEncode($Password)

$databaseUrl = "postgresql+asyncpg://${DbUser}:${encodedPassword}@${DbHost}:${DbPort}/${DbName}"
$envPath = Join-Path $ProjectRoot ".env"
$envContent = @"
# Generated by scripts/setup-db.ps1 - local PostgreSQL (do not commit)
DATABASE_URL=$databaseUrl
"@

# UTF-8 without BOM so Python dotenv reads DATABASE_URL correctly
[System.IO.File]::WriteAllText($envPath, $envContent, (New-Object System.Text.UTF8Encoding $false))

Write-Host ".env written to $envPath"

Write-Host "Verifying via Python..."
.\.venv\Scripts\python.exe -c @"
import asyncio
from dotenv import load_dotenv
load_dotenv()
from backend.db.init_db import init_db
ok = asyncio.run(init_db())
print('DB init:', 'OK' if ok else 'FAILED')
exit(0 if ok else 1)
"@

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "Done. Restart the backend: .\scripts\start-backend.ps1"
    Write-Host "Health check should show: `"database`": `"connected`""
} else {
    Write-Error "Python DB init failed. Check .env and PostgreSQL."
}
